"""Runtime Scripts extension for Sutra OS — bridge-client edition.

All task validation and file I/O live in the host-side dispatcher_bridge.py daemon.
This extension is a thin HTTP client that talks to the bridge over
http://host.docker.internal:PORT using a shared bearer token.

Configure via Settings > Integrations > Extensions:
  bridge_url   (config)      — e.g. http://host.docker.internal:7475
  bridge_token (credential)  — shared bearer token (set by install.sh)

Provides:
  - runtime_scripts_add_task:      queue a task into tasks.md
  - runtime_scripts_trigger_run:   fire-and-forget scripts/run.sh via the bridge
  - runtime_scripts_list_tasks:    show pending / in_progress / done
  - runtime_scripts_get_status:    show active task, plan, needs-human, logs
"""

from __future__ import annotations

import json
from typing import Any

from langchain_core.tools import tool

EXTENSION_MANIFEST = {
    "id": "runtime_scripts",
    "name": "Dispatcher",
    "description": "Dispatch tasks to the autonomous runner via the host-side bridge daemon",
    "icon": "workflow",
    "version": "2.0.0",
    "author": "Sutra Community",
    "credential_fields": [
        {
            "key": "bridge_token",
            "label": "Bridge Token",
            "secret": True,
            "placeholder": "Generated by install.sh — see DISPATCHER_BRIDGE_TOKEN in backend/.env",
        },
    ],
    "config_fields": [
        {
            "key": "bridge_url",
            "label": "Bridge URL",
            "secret": False,
            "placeholder": "http://host.docker.internal:7475",
        },
    ],
    "tool_ids": [
        "runtime_scripts_add_task",
        "runtime_scripts_trigger_run",
        "runtime_scripts_list_tasks",
        "runtime_scripts_get_status",
    ],
    "is_dangerous": True,
}


async def _get_bridge(agent_id: str) -> tuple[str, str]:
    """Return (bridge_url, bridge_token) from the integration row."""
    from sqlalchemy import nullslast, select

    from app.core.vault import decrypt_secret
    from app.db.session import async_session_factory
    from app.models.integration import Integration

    async with async_session_factory() as db:
        result = await db.execute(
            select(Integration)
            .where(Integration.type == "runtime_scripts", Integration.is_active == True)  # noqa: E712
            .order_by(nullslast(Integration.agent_id.desc()))
        )
        rows = result.scalars().all()

    agent_specific = next((r for r in rows if r.agent_id == agent_id), None)
    system_wide    = next((r for r in rows if r.agent_id is None), None)
    row = agent_specific or system_wide

    if not row:
        raise ValueError(
            "No active 'runtime_scripts' integration. Re-run ./install.sh to configure the dispatcher bridge."
        )

    url = ((row.extra_config or {}).get("bridge_url") or "").rstrip("/")
    if not url:
        raise ValueError(
            "runtime_scripts integration is missing bridge_url. "
            "Re-run ./install.sh or edit the integration in Settings > Integrations."
        )

    token = ""
    if row.credentials_enc:
        try:
            creds = json.loads(decrypt_secret(row.credentials_enc))
            token = creds.get("bridge_token") or ""
        except Exception:
            pass

    if not token:
        raise ValueError(
            "runtime_scripts integration is missing bridge_token. "
            "Re-run ./install.sh to generate DISPATCHER_BRIDGE_TOKEN."
        )

    return url, token


async def _call_bridge(
    method: str,
    path: str,
    agent_id: str,
    json_body: dict[str, Any] | None = None,
) -> dict[str, Any]:
    """Call the dispatcher bridge with auth, 5 s timeout, and one retry on network errors."""
    import httpx

    url, token = await _get_bridge(agent_id)
    headers = {"Authorization": f"Bearer {token}"}
    full_url = f"{url}{path}"

    last_exc: Exception | None = None
    for attempt in range(2):
        try:
            async with httpx.AsyncClient(timeout=5.0) as client:
                if method == "GET":
                    resp = await client.get(full_url, headers=headers)
                else:
                    resp = await client.post(full_url, headers=headers, json=json_body or {})
            break
        except (httpx.ConnectError, httpx.TimeoutException) as exc:
            last_exc = exc
            if attempt == 0:
                continue
            raise ValueError(
                f"Bridge unreachable at {url} — is scripts/dispatcher_bridge.py running on the host?"
            ) from exc
    else:
        raise ValueError(
            f"Bridge unreachable at {url} — is scripts/dispatcher_bridge.py running on the host?"
        ) from last_exc

    if resp.status_code == 401:
        raise ValueError(
            "Bridge rejected the token (401) — check DISPATCHER_BRIDGE_TOKEN in backend/.env."
        )
    if not resp.is_success:
        try:
            detail = resp.json().get("detail", resp.text)
        except Exception:
            detail = resp.text
        raise ValueError(f"Bridge error {resp.status_code}: {detail}")

    return resp.json()


def create_tools(agent_id: str):
    @tool
    async def runtime_scripts_add_task(
        task_id: str,
        repo: str,
        branch: str,
        goal: str,
        priority: str = "P2",
        complexity: str = "normal",
        ultrathink: bool = False,
        test: str = "npm test",
        note: str = "",
    ) -> str:
        """Dispatch a task to the runner's tasks.md queue under `## pending`.

        Executes on the host via the dispatcher bridge daemon. Use this when the
        user asks to dispatch, queue, schedule, or hand off a task to the
        dispatcher for autonomous execution.

        Args:
            task_id: Unique slug for this task (e.g. 'fix-login-500').
            repo: Absolute path to the target repo the runner should modify.
            branch: Task branch. MUST NOT be main/master/develop/release*/prod/production.
            goal: What to do. 1-5 lines; specific enough that no follow-up is needed.
            priority: P0 (urgent), P1, or P2 (default).
            complexity: 'trivial' (one-shot), 'normal' (default), or 'complex'.
            ultrathink: Only honored when complexity='complex'; enables deep thinking.
            test: Test command run from repo root. Default 'npm test'.
            note: Optional constraints / context for the planner.
        """
        result = await _call_bridge(
            "POST", "/tasks", agent_id,
            json_body={
                "task_id": task_id, "repo": repo, "branch": branch, "goal": goal,
                "priority": priority, "complexity": complexity,
                "ultrathink": ultrathink, "test": test, "note": note,
            },
        )
        msg = result.get("message", f"Task '{task_id}' added.")
        return f"{msg} Call runtime_scripts_trigger_run to execute it."

    @tool
    async def runtime_scripts_trigger_run() -> str:
        """Trigger the dispatcher runner (scripts/run.sh) via the bridge daemon.

        Spawns run.sh as a detached background process on the host and returns
        immediately with a log path. run.sh enforces its own safety gates
        (lockfile, session-reset window, weekly budget, needs-human escalation)
        and may no-op. Use runtime_scripts_get_status to inspect progress.
        """
        result = await _call_bridge("POST", "/trigger", agent_id)
        pid = result.get("pid")
        log_path = result.get("log_path", "(unknown)")
        return (
            f"Launched run.sh on host (pid {pid}). Output streaming to {log_path}. "
            "run.sh may no-op if its session-reset gate hasn't elapsed; "
            "check runtime_scripts_get_status for the outcome."
        )

    @tool
    async def runtime_scripts_list_tasks() -> str:
        """List dispatcher tasks by section (pending / in_progress / done)."""
        result = await _call_bridge("GET", "/tasks", agent_id)
        pending     = result.get("pending", [])
        in_progress = result.get("in_progress", [])
        done        = result.get("done", [])

        def _fmt(ids: list[str]) -> str:
            return f"{len(ids)} task(s)" + (f" — {', '.join(ids)}" if ids else "")

        return (
            f"  pending:     {_fmt(pending)}\n"
            f"  in_progress: {_fmt(in_progress)}\n"
            f"  done:        {_fmt(done)}"
        )

    @tool
    async def runtime_scripts_get_status() -> str:
        """Report dispatcher runner status: active task, plan, needs-human, recent logs."""
        result = await _call_bridge("GET", "/status", agent_id)
        active       = result.get("active_task") or "(none)"
        plan         = result.get("plan_progress") or "(none)"
        needs_human  = result.get("needs_human")
        recent_logs  = result.get("recent_logs", [])

        lines = [
            f"  active task:  {active}",
            f"  plan:         {plan}",
            f"  needs-human:  {'YES — ' + needs_human if needs_human else 'no'}",
        ]
        if recent_logs:
            lines.append("  recent logs:")
            for entry in recent_logs:
                lines.append(f"    {entry['name']} ({entry['bytes']} bytes)")
        else:
            lines.append("  recent logs: (none)")
        return "\n".join(lines)

    return [
        runtime_scripts_add_task,
        runtime_scripts_trigger_run,
        runtime_scripts_list_tasks,
        runtime_scripts_get_status,
    ]


async def test_connection(creds: dict, config: dict) -> dict:
    """Verify the bridge is reachable and authenticated."""
    import httpx

    url = (config.get("bridge_url") or "").rstrip("/")
    token = creds.get("bridge_token") or ""

    if not url:
        return {"ok": False, "detail": "bridge_url is empty."}

    try:
        async with httpx.AsyncClient(timeout=5.0) as client:
            resp = await client.get(
                f"{url}/health",
                headers={"Authorization": f"Bearer {token}"} if token else {},
            )
    except (httpx.ConnectError, httpx.TimeoutException) as e:
        return {"ok": False, "detail": f"Bridge unreachable at {url}: {e}"}

    if resp.status_code == 401:
        return {"ok": False, "detail": "Bridge rejected token (401)."}
    if not resp.is_success:
        return {"ok": False, "detail": f"Bridge returned {resp.status_code}."}

    data = resp.json()
    if not data.get("ok"):
        return {"ok": False, "detail": f"Bridge running but base_path invalid: {data.get('base_path')}"}

    return {"ok": True, "detail": f"Connected: {url} (base_path={data.get('base_path')})"}
