"""Data analysis tools using pandas for AI agents."""

import ast
import io
import os
import sys
from typing import Any

import pandas as pd
from langchain_core.tools import tool

from app.tools.os_tools import _is_path_allowed

# AST node types that are never allowed in agent-submitted code.
_BLOCKED_AST_NODES = (
    ast.Import,
    ast.ImportFrom,
)

# Built-in names that are forbidden inside the sandbox.
_BLOCKED_BUILTINS = {
    "exec", "eval", "compile", "__import__", "open",
    "breakpoint", "exit", "quit", "globals", "locals",
    "getattr", "setattr", "delattr", "vars", "dir",
    "memoryview", "type", "classmethod", "staticmethod",
    "super", "property",
}

# Minimal safe builtins exposed to the sandbox.
_SAFE_BUILTINS = {
    k: v for k, v in __builtins__.items()  # type: ignore[union-attr]
    if k not in _BLOCKED_BUILTINS
} if isinstance(__builtins__, dict) else {
    k: getattr(__builtins__, k)
    for k in dir(__builtins__)
    if k not in _BLOCKED_BUILTINS and not k.startswith("_")
}


def _validate_code(source: str) -> str | None:
    """Parse *source* and return an error message if it uses blocked constructs."""
    try:
        tree = ast.parse(source)
    except SyntaxError as e:
        return f"Syntax error in submitted code: {e}"

    for node in ast.walk(tree):
        if isinstance(node, _BLOCKED_AST_NODES):
            return (
                "Import statements are not allowed. "
                "Only pandas (pd) and the loaded DataFrame (df) are available."
            )
        # Block access to dunder attributes (e.g. __class__, __subclasses__)
        if isinstance(node, ast.Attribute) and node.attr.startswith("__"):
            return f"Access to dunder attributes ('{node.attr}') is not allowed."
    return None


@tool
def analyze_data(file_path: str, python_code: str) -> str:
    """Load a CSV or Excel file into a pandas DataFrame (named 'df') and execute Python code to analyze it.

    Args:
        file_path: Absolute path to the CSV or Excel file on disk.
        python_code: Python code to execute. The dataset is already loaded into a variable named 'df'. Use print() to output your results. Import statements are not allowed — only pandas (pd) and the DataFrame (df) are available.

    Returns:
        The standard output generated by your Python code, or an error message.
    """
    path = os.path.expanduser(file_path)
    if not _is_path_allowed(path):
        return f"Access Denied: The path '{file_path}' is outside the allowed directories."

    if not os.path.exists(path):
        return f"Error: File '{file_path}' does not exist."

    # --- Static validation ---------------------------------------------------
    validation_error = _validate_code(python_code)
    if validation_error:
        return f"Code rejected: {validation_error}"

    # --- Load the dataframe --------------------------------------------------
    try:
        if path.lower().endswith(".csv"):
            df = pd.read_csv(path)
        elif path.lower().endswith((".xls", ".xlsx")):
            df = pd.read_excel(path)
        else:
            return f"Error: Unsupported file format for '{file_path}'. Please provide a .csv, .xls, or .xlsx file."
    except Exception as e:
        return f"Error loading file into pandas: {e}"

    # --- Sandboxed execution -------------------------------------------------
    sandbox_globals: dict[str, Any] = {
        "__builtins__": _SAFE_BUILTINS,
        "pd": pd,
        "df": df,
    }

    old_stdout = sys.stdout
    redirected_output = sys.stdout = io.StringIO()

    try:
        exec(compile(python_code, "<agent-code>", "exec"), sandbox_globals)
    except Exception as e:
        sys.stdout = old_stdout
        return f"Error executing Python code:\n{e}"
    finally:
        sys.stdout = old_stdout

    output = redirected_output.getvalue()
    if not output.strip():
        output = "Code executed successfully but produced no output. Did you forget to print() the results?"

    return output
