"""Data analysis tools using pandas for AI agents."""

import io
import os
import sys
from typing import Any

import pandas as pd
from langchain_core.tools import tool

from app.tools.os_tools import _is_path_allowed


@tool
def analyze_data(file_path: str, python_code: str) -> str:
    """Load a CSV or Excel file into a pandas DataFrame (named 'df') and execute Python code to analyze it.
    
    Args:
        file_path: Absolute path to the CSV or Excel file on disk.
        python_code: Python code to execute. The dataset is already loaded into a variable named 'df'. Use print() to output your results.
    
    Returns:
        The standard output generated by your Python code, or an error message.
    """
    path = os.path.expanduser(file_path)
    if not _is_path_allowed(path):
        return f"Access Denied: The path '{file_path}' is outside the allowed directories."
        
    if not os.path.exists(path):
        return f"Error: File '{file_path}' does not exist."
        
    # Load the dataframe
    try:
        if path.lower().endswith(".csv"):
            df = pd.read_csv(path)
        elif path.lower().endswith((".xls", ".xlsx")):
            df = pd.read_excel(path)
        else:
            return f"Error: Unsupported file format for '{file_path}'. Please provide a .csv, .xls, or .xlsx file."
    except Exception as e:
        return f"Error loading file into pandas: {e}"
        
    # Prepare execution environment
    local_vars: dict[str, Any] = {"df": df, "pd": pd}
    
    # Capture stdout
    old_stdout = sys.stdout
    redirected_output = sys.stdout = io.StringIO()
    
    try:
        # Execute the AI-provided code safely
        exec(python_code, {}, local_vars)
    except Exception as e:
        sys.stdout = old_stdout
        return f"Error executing Python code:\n{e}"
    finally:
        sys.stdout = old_stdout
        
    output = redirected_output.getvalue()
    if not output.strip():
        output = "Code executed successfully but produced no output. Did you forget to print() the results?"
        
    return output
