#!/bin/bash
# render-host-mounts.sh — generate docker-compose.override.yml from the
# ALLOWED_AGENT_FILE_PATHS allowlist in backend/.env.
#
# Each path is mounted at the identical path inside the backend + celery
# containers, so integration `base_path` values (e.g. the runtime_scripts
# extension) work unchanged between host and container.
#
# Usage:
#   scripts/render-host-mounts.sh          # regenerate, picking up any .env edits
#
# Called automatically by start.sh before `docker compose up`.
set -euo pipefail

PROJECT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$PROJECT_DIR"

ENV_FILE="backend/.env"
OUT="docker-compose.override.yml"
HEADER="# Auto-generated by scripts/render-host-mounts.sh — DO NOT EDIT.
# Regenerate by editing ALLOWED_AGENT_FILE_PATHS in backend/.env
# and re-running ./start.sh (or scripts/render-host-mounts.sh directly)."

paths_csv=""
if [ -f "$ENV_FILE" ]; then
    # Last non-commented ALLOWED_AGENT_FILE_PATHS= line wins.
    paths_csv=$(grep -E '^[[:space:]]*ALLOWED_AGENT_FILE_PATHS[[:space:]]*=' "$ENV_FILE" \
                | tail -1 \
                | sed -E 's/^[^=]*=//; s/^["'\'']//; s/["'\'']$//')
fi

valid_mounts=()
skipped=()

if [ -n "${paths_csv:-}" ]; then
    IFS=',' read -ra arr <<< "$paths_csv"
    for raw in "${arr[@]}"; do
        p="$(echo "$raw" | awk '{$1=$1;print}')"  # trim outer whitespace
        [ -z "$p" ] && continue
        if [[ "$p" != /* ]]; then
            skipped+=("$p (not absolute)")
            continue
        fi
        if [[ "$p" == *":"* ]]; then
            skipped+=("$p (contains ':')")
            continue
        fi
        if [ ! -e "$p" ]; then
            skipped+=("$p (does not exist)")
            continue
        fi
        valid_mounts+=("$p")
    done
fi

if [ "${#valid_mounts[@]}" -eq 0 ]; then
    # Nothing to mount — remove any stale override so compose isn't confused.
    if [ -f "$OUT" ]; then
        rm -f "$OUT"
        echo "render-host-mounts: no valid paths in ALLOWED_AGENT_FILE_PATHS — removed stale $OUT"
    else
        echo "render-host-mounts: no valid paths in ALLOWED_AGENT_FILE_PATHS — nothing to do"
    fi
    for s in "${skipped[@]:-}"; do
        [ -n "$s" ] && echo "  skipped: $s"
    done
    exit 0
fi

{
    echo "$HEADER"
    echo "services:"
    for svc in backend celery; do
        echo "  $svc:"
        echo "    volumes:"
        for p in "${valid_mounts[@]}"; do
            echo "      - \"$p:$p\""
        done
    done
} > "$OUT"

echo "render-host-mounts: wrote $OUT with ${#valid_mounts[@]} mount(s):"
for p in "${valid_mounts[@]}"; do
    echo "  + $p"
done
for s in "${skipped[@]:-}"; do
    [ -n "$s" ] && echo "  ! skipped: $s"
done
